[package]
name = "pollard-kangaroo"
version = "0.0.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
reqwest = { version = "0.12.9", features = ["blocking"] }
serde_json = "1.0.133"
serde = { version = "1.0.216", features = ["derive"] }
curve25519-dalek-ng = "4"
hex = { version = "0.4", features = ["serde"] }
rand = "0.8"
rand_core = { version = "0.6", default-features = false }
anyhow = { version = "1.0", default-features = false }
wasm-bindgen = "0.2.99"
js-sys = "0.3.76"

[lib]
crate-type = ["cdylib", "rlib"]
